Task 18 badges
galuropek/rails_basic pull request #18
Opened 2021-10-10 20:11 UTC by galuropek

Бейджи юзера отображаются в навбаре

2021-10-11 07:25 UTC, BubuntuClu requested changes

2021-10-11 07:25 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      badges = @rules.map { |rule| rule.accept!(@test_passage) }.compact
это надо вынести в сервис, который будет отвечать за награждение и проверку

2021-10-11 07:25 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :set_rules, only: :update
ради одного метода не надо делать колбэк. колбэки вообще плохая практика

2021-10-11 07:25 UTC, BubuntuClu commented on app/models/category.rb
> +  has_many :rules
что за правила у категории? это что-то не то. бейдж должен хранить в себе правило

2021-10-11 07:25 UTC, BubuntuClu commented on app/models/rule.rb
> +  belongs_to :category
почему оно принадлежит категории? что-то не уловил я эту логику

2021-10-11 07:25 UTC, BubuntuClu commented on app/models/category_rule.rb
> +class CategoryRule < Rule
как много кода. попытка через объектную модель это прикольно, но чет вышло как-то сложно. если сделать через методы в сервисе, то выходит по 3 строки на каждую проверку.
в каждом правиле ты задаешь начальные значения, не очень практично. стоит один раз задать и перебирать все баджи

2021-10-11 07:25 UTC, BubuntuClu commented on app/models/category_rule.rb
> +  MSG = 'Вы получили бэйдж за прохождение всех тестов в категории "%s"!'.freeze
имена переменных лучше не сокращать. ты ничего не потеряешь от полного наименования, зато повысишь читабельность кода

2021-10-11 07:25 UTC, BubuntuClu commented on app/models/category_rule.rb
> +    success_tests = success_passages.map(&:test)
собирай данные через запросы к БД.

метод может выглядеть примерно так
```
1 - запрос на получение всех тестов категории
2 - запрос на получение пройденных тестов категории
3 - 1 == 2?
```

2021-10-13 08:25 UTC, BubuntuClu approved these changes

2021-10-13 08:25 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    badge.notification = "Вы получили ачивку за прохождение всех тестов из категории %s" % badge.value
это стоит выставлять только если у тебя проверка прошла, раньше какой смысл?

2021-10-13 08:25 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    badge.notification = "Вы получили ачивку за прохождение всех тестов из категории %s" % badge.value
да и вообще это как-то странно смотрится, делать `attr_accessor` чтобы закостылить ументь задать навзвание. может просто поле в badge добавить для отображения текста?

2021-10-13 08:25 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    success_tests_from_category = @success_tests.by_category_name(badge.value).distinct.count
сначала ты делаешь запрос, чтобы получить `@success_tests`. а потом делаешь запрос чтобы отфильтровать его. получается 2 запроса, не очень круто. стоит переделать на один

2021-10-13 18:21 UTC, galuropek commented
сделал исправления

2021-10-13 18:21 UTC, merged