Task 3 rails models
galuropek/rails_basic pull request #3
Opened 2021-08-15 19:30 UTC by galuropek

Создал модели сущностей для проекта.
Добавил not null миграции для некоторых обязательных полей.
Добавил значения по умолчанию для некоторых полей.

2021-08-16 06:39 UTC, BubuntuClu requested changes

2021-08-16 06:39 UTC, BubuntuClu commented on db/migrate/20210815184132_create_tests.rb
> +
нужно добавить связь с таблицей категорий. не забудь внешний ключ и индекс. правки вносить в этот файл

2021-08-16 06:39 UTC, BubuntuClu commented on db/migrate/20210815184453_create_questions.rb
> +
нужно добавить связь с таблицей тестов. не забудь внешний ключ и индекс. правки вносить в этот файл

2021-08-16 06:39 UTC, BubuntuClu commented on db/migrate/20210815184547_create_answers.rb
> +
нужно добавить связь с таблицей вопросов. не забудь внешний ключ и индекс. правки вносить в этот файл

2021-08-16 09:40 UTC, galuropek commented
Сделал новый коммит: добавил связи и индексы для нужных таблиц, перенес изменения моделей в основные миграции.

2021-08-16 17:30 UTC, BubuntuClu approved these changes

2021-08-16 17:30 UTC, BubuntuClu commented on db/migrate/20210815184132_create_tests.rb
> +    # add_index :tests, :category_id
неиспользуемый код не стоит тащить в репозиторий. `references` под капотом создает индекс. можно удалить эти строки из всех миграций

2021-08-16 17:30 UTC, BubuntuClu commented on db/migrate/20210815184132_create_tests.rb
> +      t.references :category, index: true, foreign_key: true
`index: true` тут лишнее, так как `references` под капотом создает индекс

2021-08-16 17:30 UTC, BubuntuClu commented on db/migrate/20210815184132_create_tests.rb
> +      t.references :category, index: true, foreign_key: true
этой командой ты создаешь внешний ключ к таблице категорий, но таблицы категорий у тебя еще нет, так как судя по миграциям она создается послденей. в БД оличных от sqlite ты получишь ошибку

2021-08-16 17:30 UTC, BubuntuClu commented on db/schema.rb
> +  add_index "answers", ["question_id"], name: "index_answers_on_question_id"
( -_-)

2021-08-16 19:58 UTC, galuropek commented on db/migrate/20210815184132_create_tests.rb
> +      t.references :category, index: true, foreign_key: true
Спасибо, очень полезные замечания. Я вроде как понял, что нужно сделать, но сомневаюсь в одном пункте. Правильно ли будет, если я изменю timestamp в названии миграции, которая создает таблицу categories, чтобы передвинуть ее вперед и она создавалась раньше таблицы tests при команде db:migrate? Или есть более правильный способ исправить этот косяк?

2021-08-17 05:53 UTC, galuropek commented
Убрал `index: true` из миграций. Переименовал миграцию создания таблицы категорий (изменил таймстемп), чтобы она создавалась раньше таблицы тестов.

2021-08-17 16:29 UTC, merged