Task 7 controllers
galuropek/rails_basic pull request #7
Opened 2021-08-29 07:27 UTC by galuropek

Создал ресурс Вопросов, вложенный в ресурс Тестов
Создал контроллеры вопросов и тестов
Создал view для добавления нового вопроса
Остальные ответы клиенту выполнил через рендер plain text или HTM, как сказано в задании
Реализовал метод destroy для вопросов, удаление можно сделать через questions#show
Добавил обратный вызов при поиске теста и исключения для случая когда вопрос не был найден

2021-08-29 18:09 UTC, BubuntuClu requested changes

2021-08-29 18:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
этот код дублируется в нескольких методах. стоит вынести в коллбэк/метод

2021-08-29 18:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test.questions.create(question_params)
параметры могут быть невалидные, надо это учесть при создании объекта

```
question = @test.questions.new(question_params)
if question.save
  render good
else
  render bad
end
```

2021-08-29 18:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path
для какого теста будут отбражаться вопросы?

2021-08-29 18:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render plain: Question.all.map(&:body).join("\n")
у тебя ресурс вопросов вложен в ресурс тестов. это значит что вопросы принадлежат какому-то тесту. нельзя показывать все вопросы, только те что принадлежат текущему тесту

2021-08-29 18:09 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="<%= test_questions_path %>" method="post">
что-то у меня сомнения на счет этой строки. она работает? мне кажется, ты аргумент забыл передать

2021-08-29 18:09 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь для вопросов опцию `shallow: true`, посмотри как изменяться пути и адаптируй код под эти изменения

2021-08-30 18:27 UTC, galuropek commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path
До добавления `shallow: true` к вопросам такой путь работал вроде как корректно, id теста был в параметрах:
```
(byebug) test_questions_path
"/tests/2/questions"
```

2021-08-30 18:38 UTC, galuropek commented on app/views/questions/new.html.erb
> +<form action="<%= test_questions_path %>" method="post">
Это работает. Возможно я что-то упускаю, но я протестировал создание для 2-го теста через браузер, проверил в дебаггере - путь выглядит как в маршрутах:
```
(byebug) test_questions_path
"/tests/2/questions"
```

```
POST   /tests/:test_id/questions(.:format)     questions#create
```

2021-08-30 18:55 UTC, galuropek commented
Вынес поиск вопроса в колбэк.
Добавил проверку при создании вопроса.
Исправил список вопросов в методе `index`: теперь выводятся вопросы только конкретного теста.
Добавил для вопросов `shallow: true`.

2021-08-31 06:25 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="<%= test_questions_path %>" method="post">
хм, странно. видать рельсы становятся еще умней)

2021-08-31 18:50 UTC, merged