Task 9 application logic
galuropek/rails_basic pull request #9
Opened 2021-09-04 14:41 UTC by galuropek

Создал модель TestPassage.
Сделал назначение следующего вопроса в модели TestPassage с помощью обратного вызова.
Добавил вывод сообщения о прохождении теста зависящий от количества корректно пройденных вопросов.
Добавил вывод номера текущего вопроса и общее количество вопросов теста.

2021-09-04 17:18 UTC, BubuntuClu requested changes

2021-09-04 17:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
не нужно делать ответ для тех форматов, которые ты не поддерживаешь. ты загромождаешь себя ненужным кодом. убери этот блок и сделай без него

2021-09-04 17:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создаем через ассоциацию вопроса

2021-09-04 17:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
и тут блок этот не нужен

2021-09-04 17:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
и тут

2021-09-04 17:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
а куда ведет эта ссылка?

2021-09-04 17:18 UTC, BubuntuClu commented on db/migrate/20210903182031_drop_table_tests_users.rb
> +  def up
если есть `up` то должен быть и `down`, чтобы миграция могла откатиться без ошибки. в данном случае `down` можно оставить пустым

2021-09-04 17:18 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +<% if valid_result?(@test_passage, threshold: 85) %>
это похоже на метод модели.  `test_passage.success?`, в котором ты проверяешь результат.

а что такое 85? не понятно без контектса. вынеси в модель, в константу и обзови понятно

2021-09-04 17:18 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    test_passage.test.questions.order(:id).index(test_passage.current_question).next
выглядит как метод модели

2021-09-05 07:31 UTC, galuropek commented
Изначально не отредактировал модель `Answer` после скафолдинга, оставил как есть (моя ошибка).
Исправил модель Answer: убрал лишнее из контроллера, исправил маршруты, шаблоны.
Перенес вспомогательные методы `success?` и `question_number` из хелперов в модель `TestPassage`, так как по логике они относятся к конкретной модели.
Добавил метод `down` в миграцию `drop_table`.

2021-09-06 18:47 UTC, merged